### ISSUE TITLE
Retours HOME PAGE

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#1]
**Bloc Logement & Transport :**  Changez la phrase _« Retrouvez ..dans leur assiette »_ 
Proposition : 
=> « Aidez vos utilisateurs à découvrir l’impact environnemental de leur déplacement. »
=>« Aidez vos utilisateurs à la rénovation et la décarbonation du secteur du bâtiment. »

**Newsletter :** Remonter au-dessus de contact + la démarquer pour que ça ne fasse pas deux formulaires à la suite. (Proposition => picto enveloppe). 
Et du coup de base on avait un formulaire contact pour la newsletter on le supprime pour qu’il n’ait juste plus qu’à rentrer l’email ? 

**Nos jeux de données :** : Remonter du coup le bloc pour l’intégrer sous NOS SIMULATEURS

**Footer :** rajouter réseaux sociaux du coup Linkedin + Twitter + est-ce qu’on rajoute GIT ? Je voyais que sur le site de beta.gouv il le mettait. 
On remet la description de ce que l’on fait dans le footer ?

**Menu** : Grossir / Graisser le menu pour qu’il soit plus visible

**Logo Datagir** : parti pris de ne plus le mettre sur la HP en haut à gauche avec les autres logos. Je trouve ça un peu bizarre, qu’il réapparaisse après par contre sur les autres pages. 
Pq ne pas mettre le logo Datagir en simple vert (sans le bloc) en haut à gauche en statique ?

**Comment by martinregner** [comment]
Ok avec tout ça :)

Quelques compléments :

> Bloc Logement & Transport : Changez la phrase « Retrouvez ..dans leur assiette »
Proposition :
=> « Aidez vos utilisateurs à découvrir l’impact environnemental de leur déplacement. »
=>« Aidez vos utilisateurs à la rénovation et la décarbonation du secteur du bâtiment. »

J'arrive pas à retrouver cette page dans le figma, mais les textes étaient pas mal initialement, mais je trouve ces propositions très bien aussi 👍 

> Newsletter : Remonter au-dessus de contact + la démarquer pour que ça ne fasse pas deux formulaires à la suite. (Proposition => picto enveloppe).
Et du coup de base on avait un formulaire contact pour la newsletter on le supprime pour qu’il n’ait juste plus qu’à rentrer l’email ?

Ca a toujours été un (mini) formulaire avec que l'email + "secteurs Ecolab" (retirés)
Par contre @florianpanchout ça pose la question de la connexion avec SendinBlue. Aujourd'hui c'était un iframe SendinBlue paramétrable. 

**Nos Simulateurs :** on pourrait les trier par ordre alphabétique ? ;)

> Pq ne pas mettre le logo Datagir en simple vert (sans le bloc) en haut à gauche en statique ?

+1 Etrange de ne pas avoir de logo en haut. L'association du logo précédent avec les autres logos passaient bien je trouve

**Comment by martinregner** [comment]
Ca passe bien sinon je trouve l'un sur l'autre avec le logo dans l'autre sens :

![image](https://user-images.githubusercontent.com/46482115/107376067-bfa33300-6ae9-11eb-8c43-444bd0738eec.png)
![image](https://user-images.githubusercontent.com/46482115/107376096-c762d780-6ae9-11eb-9db4-b856eaee2172.png)

**Comment by florianpanchout** [comment]
A l'avenir,  ce serait plus pratique pour moi d'avoir une issue par bug / modification :) Je crée une nouvelle issue pour le nouveau design du formulaire newsletter

Pour les blocs logement et transport, sur le Figma (et l'ancien site) on avait : "Aidez vos utilisateurs à découvrir l’impact environnemental de leur logement et sa consommation énergétique." pour logement. J'ai remis celui la qui est sur le même modèle que les deux autres.
