### ISSUE TITLE
Logos  RF + ADEME pixelisés

### ISSUE THREAD

**Issue by martinregner** [betagouv/datagir-site#11]
Les logos du header sont un peu pixélisés de mon côté (pas ceux du footer) :
![image](https://user-images.githubusercontent.com/46482115/107387851-8244a280-6af5-11eb-9bf5-01d0d8ee4c36.png)

**Comment by florianpanchout** [comment]
C'est corrigé !

**Comment by martinregner** [comment]
Tu as fait un effet dessus ? Je vois en rechargeant qu'ils sont pixélisés puis se mettent en net.

**Comment by florianpanchout** [comment]
Yes c'est pour que la page se charge plus rapidement. Mais ça n'a effectivement pas trop de sens de l'afficher sur les logos, j'ai supprimé

**Comment by martinregner** [comment]
ils apparaissent d'un coup, c'est parfait :)
