### ISSUE TITLE
Sections "Nos simulateurs" sur les pages secteurs

### ISSUE THREAD

**Issue by martinregner** [betagouv/datagir-site#15]
1. Je propose d'uniformiser pour avoir un CTA vers les simulateurs pour chaque secteur dès le début de la page (cf. #12 ; #13)
2. Dans la section Nos Simulateurs du secteur, je propose de :
- mettre en premier le calculateur du secteur concerné (sauf pour logement pour l'instant ^^)
- modifier le texte en **Nos Simulateurs en lien avec le _Nom du secteur_**

**Comment by florianpanchout** [comment]
C'est fait ! (je me suis permis de changer "en lien avec" par "liés à")

**Comment by martinregner** [comment]
Nickel !  👍 👍
