### ISSUE TITLE
Trier les simulateurs par ordre alphabétique

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/datagir-site#16]
On peut changer l'ordre des simulateurs via le paramètre "order" dans les fiches simulateurs. Par contre est ce que ce n'est pas plus interessant de les trier par ordre "d'importance" plutôt qu'alphabétique ?

**Comment by martinregner** [comment]
Je me disais que par ordre alpha les visiteurs pouvaient plus facilement les retrouver ... et ça coupe le débat sur c'est quoi " le plus important". Pour les utilisateurs le plus important est celui qui leur parle + donc, alimentation pour ceux qui sont sur ce secteur, MCC pour les plutôt RSE ...
Pour arriver à trouver une métrique d'importance plus "globale", c'est "l'impact grand public" associé / les changements de comportement. A mon sens ce serait :
1. NGC
2. MCC
3. MIT (ou pourquoi pas en 2)
4. MFLS

**Comment by florianpanchout** [comment]
On a que 4 simulateurs et leurs noms commencent par "Mes", "Mon" et "Nos". Je ne suis pas sur que ça soit pertinent de les trier par ordre alphabétique.

Ceci étant dit... on a 4 simulateurs. On peut les trier n'importe comment ça ne changera pas grand chose

**Comment by martinregner** [comment]
> Ceci étant dit... on a 4 simulateurs. On peut les trier n'importe comment ça ne changera pas grand chose

C'est sûr ! 😄 Le 4ème est désavantagé il a un scroll (ou 2) de plus 😋 

Je comprenais juste pas la logique d'affichage (peut-être garder les 3 catégories / les 3 couleurs en premières lignes ?) ... mais restons comme ça
