### ISSUE TITLE
Intro page jeu de données

### ISSUE THREAD

**Issue by martinregner** [betagouv/datagir-site#19]
- Je propose pour le carré vert :
**Des données environnementales ouvertes pour agir.**

- Dans la partie intro en blanc : 
**L’ADEME met à disposition de manière ouverte de nombreux jeux de données. Datagir vous accompagne dans la compréhension et l’intégration de ces données afin de vous aider à créer de nouvelles fonctionnalités et applications pour la transition écologique.**

- Bouton de gauche : "**Découvrir les ressources Datagir**" --> https://datagir.gitbook.io/documentation
- Bouton de droite : "**Voir tous les jeux de données**" --> https://data.ademe.fr/datasets

@Clem-mrtn tu en penses quoi ?

**Comment by florianpanchout** [comment]
C'est en ligne !

**Comment by martinregner** [comment]
top ! 👍
