### ISSUE TITLE
Remplacer le logo Ecolab sur tous les simulateurs 

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#2]
Logo Ecolab encore visible sur les embeded de tous les simulateurs et sur leurs LP.
Le remplacer par le logo Datagir ?

**Comment by martinregner** [comment]
Sur ce sujet, je viens d'avoir un retour en interne (pourtant quelqu'un qui connait bien ce qu'on fait) : 

> l'adresse de la page est "anonyme" et souvent mon premier reflexe est de cliquer sur "qui sommes nous ?" ou équivalent.
> là, faut scrooler jusqu'en bas.... pour être rassuré !

De plus, beaucoup de sites mettent le logo ADEME sans qu'on sache trop "qui ils sont" ou le lien avec l'ADEME (parfois juste parce qu'ils utilisent les données, ou ont eu un financement, etc.)
Sans aller ajouter nécessairement un logo en haut, je vois plusieurs pistes :

1.  écrire que c'est un service ou un site de l'ADEME ; il y a des logos "endossement" qui existent (plutôt pour les partenaires), ex. ci-dessous. On peut éventuellement créer un spécifique "Un site" ou "Un service" :
![Endossement_Vert_Promu](https://user-images.githubusercontent.com/46482115/107383663-81117680-6af1-11eb-88ef-8f21d20bdc38.jpg)

2. Plus simple : on rend juste cliquable tout le bloc logo qui amène vers la landing
3. On ajoute un "en savoir plus" par là

Là comme ça, la 2. me semble suffisante.
Qu'en pensez-vous @Clem-mrtn @florianpanchout ?

**Comment by Clem-mrtn** [comment]
Quelle landing ?
Mais sinon oui bonne idée !

**Comment by martinregner** [comment]
> Quelle landing ?
datagir.ademe.fr je voulais dire :)

**Comment by martinregner** [comment]
Merci @florianpanchout pour le changement ! 👍 
Parfait le lien sur Datagir. Par contre, pour garder un max de lead entrant (et ne pas envoyer sur le site de l'ADEME bien trop vaste), je pense qu'on peut rendre tous les logos renvoient vers notre site. Ce bloc de logos est finalement aussi celui de notre landing.
Comme ça on garde le lead :)

Qu'en penses-tu ?

**Comment by florianpanchout** [comment]
Effectivement, oubli de ma part pour les embed. C'est corrigé !
Et les 3 logos amènent maintenant vers datagir

**Comment by martinregner** [comment]
Top!
Je vois que par ex. sur le site de l'ADEME le logo Datagir n'est pas chargé. Peut-être parce qu'il est animé ? Sinon tu mets la version sans animation sur les embed ?
![image](https://user-images.githubusercontent.com/46482115/108037529-063ce400-703a-11eb-91b7-8ac241b997fe.png)

https://agirpourlatransition.ademe.fr/particuliers/conso/alimentation/limpact-alimentation-lenvironnement

**Comment by florianpanchout** [comment]
Il s'affiche chez moi. Problème de cache ?

**Comment by Clem-mrtn** [comment]
Moi c'est good il s'affiche  ! 
Il manque juste le simulateur **TRANSPORT** s/ l'embeded

**Comment by martinregner** [comment]
bizarre, j'ai rechargé plusieurs fois en vidant le cache, ça ne s'affichait pas... J'ai redémarré Chrome et c'est bon 👍

**Comment by florianpanchout** [comment]
@laem J'ai créé une pull request pour le logo sur ecolab-transport

**Comment by martinregner** [comment]
c'est fait :)
