### ISSUE TITLE
Mise en forme Newsletter 

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#24]
Comme on a fermé le ticket je ne sais plus ce qu'il en est de la newsletter ? :) 

On est toujours OK pour la faire remonter au dessus de CONTACT et de la démarquer un peu plus ? (effet moins bloc peut-être pour qu'elle se démarque en terme de design ?)

**Comment by florianpanchout** [comment]
Ah oui c'est fait. J'ai remonté le block newsletter et j'ai changé son format pour qu'il soit plus lisible. Dit moi ce que tu en penses

**Comment by Clem-mrtn** [comment]
Ouiii trop bien 
Je trouve ça plus clair comme ça !
