### ISSUE TITLE
Retours réutilisateurs Homepage

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#26]
Est-ce que ce serait possible de réduire un peu la taille du caroussel ? 
Parce que sur les écrans d'ordi portable les carrés sont très gros et à moitié coupés 
![image](https://user-images.githubusercontent.com/76995768/108057328-c7675800-7052-11eb-924d-52b7cb255b62.png)

Ce serait top de pouvoir voir sur l'écran le titre Nos réutilisateurs + le caroussel en entier

**Comment by florianpanchout** [comment]
Yes j'ai design le caroussel avant d'intégrer le logo Open Food Facts qui étaient beaucoup trop gros. C'est corrigé

**Comment by Clem-mrtn** [comment]
Nickel 👍 
![image](https://user-images.githubusercontent.com/76995768/108094802-7e79c880-707f-11eb-81c6-76ed26860e6b.png)
