### ISSUE TITLE
Page Jeux donneés 

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#27]
Moi je trouve ça clair le texte pas de remarques de mon côté.
Juste question sur le design : 

Je trouve ça bizarre que les deux boutons _**"Découvrir les ressources"**_ & _**"Voir tous les jeux de données"**_  ne fassent pas la même taille : 
![image](https://user-images.githubusercontent.com/76995768/108067382-fa184d00-7060-11eb-8f8f-b368480ec04c.png)

Et pareil sur la partie BDD Carbone, l'image est à moitié coupé : 
![image](https://user-images.githubusercontent.com/76995768/108067490-26cc6480-7061-11eb-9ea7-854d64f58fce.png)

**Comment by florianpanchout** [comment]
J'ai modifié les boutons. Pour les images, c'est le principe de tous ces blocs. L'encart de texte mord sur l'image. J'ai essayé de trouver des visuels plus interessant pour la base carbone, mais ils n'ont même pas un logo officiel...
