### ISSUE TITLE
Qui sommes nous

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#38]
Intégrer le texte du fichier word 

Au sujet de la mise en page : j'aimais bien la construction que tu avais faite sur les autres pages, avec une lecture en zig zag (bloc à gauche, bloc à droite...)
Je pensais garder un peu le même format pour le Qui Sommes Nous.

+ essayer une version 2.0 de notre Offre

**Comment by florianpanchout** [comment]
J'ai mis en ligne une première version. Vous en pensez quoi @martinregner @Clem-mrtn ?

**Comment by martinregner** [comment]
Je trouve ça ca-non ! 😍 

Juste deux lien pour les derniers boutons à changer :
Découvrir nos jeux de données --> https://datagir.ademe.fr/jeux-de-donnees
Découvrir nos simulateurs --> https://datagir.ademe.fr/#applications

**Comment by florianpanchout** [comment]
C'est corrigé !

J'ai aussi fait une grosse repasse sur la version mobile. J'ai réglé pas mal de problème d'alignement et affiché les tuiles sur toute la largeur (plutôt qu'en avoir 2 côte à côte)

**Comment by Clem-mrtn** [comment]
!Yes top comme ça ! 
C'est good aussi pour moi
