### ISSUE TITLE
Ajouter une page /stats

### ISSUE THREAD

**Issue by martinregner** [betagouv/datagir-site#39]
Recréer http://datagir.ademe.fr/stats sur le même modèle que celle d'Ecolab : 

- "Iframe" matomo pour chaque calculateur + le site
- "Iframe" infogram

**Comment by florianpanchout** [comment]
https://datagir.ademe.fr/statistiques

Je n'arrive pas à voir ce que tu veux afficher via Infogram par contre

**Comment by martinregner** [comment]
Ok très bien !
(un petit **"s" en trop à climat** ;)

Sur la précédente page stats, il y avait un embed infogram à reprendre tel quel pour le moment : https://github.com/betagouv/Ecolab/blob/master/app/views/pages/stats.html.erb

**Comment by florianpanchout** [comment]
C'est fait !

**Comment by martinregner** [comment]
nickel merci !
