### ISSUE TITLE
Page simulateur Transport : Rajouter une petite description 

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/datagir-site#4]
Rajouter dans la description du simulateur une petite phrase un peu plus grand public ("encourager le rapport modal.." je trouve pas ça très parlant).
Proposition à rajouter : 
**« Découvrez l'impact des déplacements sur le climat !
Des données ouvertes pour une mobilité moins émettrice en CO2. »**

**Comment by florianpanchout** [comment]
Done
