### ISSUE TITLE
Ancien lien d'article de blog cassé

### ISSUE THREAD

**Issue by laem** [betagouv/datagir-site#46]
https://datagir.ademe.fr/blog/général/budget-empreinte-carbone-c-est-quoi.md

Je n'ai pas pigé pourquoi #7 a résolu pour cet autre lien : https://datagir.ademe.fr/blog/historique-calculateur-carbone-nos-gestes-climat-micmac-coach-carbone

@florianpanchout les redirections sont gérées à quel endroit ?

**Comment by laem** [comment]
OK j'ai trouvé c'est directement netlify : https://github.com/betagouv/datagir-site/blob/master/static/_redirects

**Comment by laem** [comment]
Je ne comprends pas pourquoi cette redir ne marche pas. C'est aussi le cas de "qui sommes nous". Le point commun, c'est le "/général"/

**Comment by laem** [comment]
@florianpanchout une idée ? ça me semble important, toutes les références à cet article qui a été plutôt bien partagé sont cassées...

**Comment by laem** [comment]
Hypothèse : la syntaxe redirects utilisée ici ne marche pas avec des accents, il faut utiliser la syntaxe complète en TOML où les chaines de caractère sont dans des crochets

**Comment by florianpanchout** [comment]
Il faut encoder les accents dans le redirect. C'est corrigé
