### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by martinregner** [betagouv/datagir-site#6]
Je trouve que le footer manque de liens ; j'aimais bien l'idée du précédent d'avoir plusieurs colonnes.
Ex : 

| A propos | Echangeons ! | Mentions légales |
| -------- | -------- | -------- |
| Qui sommes nous | Contactez-nous | données personnelles |
| Dépôts Github | LinkedIn  | gestion des cookies |
| Stats | Twitter |

Si on garde la structure actuelle avec la petite ligne tout en bas (j'ai compris que c'est le design de base), on pourrait retirer la description (cf. #1) et mettre les liens... sur 2 lignes ? (j'ai des doutes en termes de lisibilité)

**Comment by florianpanchout** [comment]
Done (en respectant le design system)
