### ISSUE TITLE
Garder les URL originales du blog 

### ISSUE THREAD

**Issue by laem** [betagouv/datagir-site#7]
Ou faire des redirections.

Par exemple, https://datagir.ademe.fr/blog/carbone/historique-calculateur-carbone-nos-gestes-climat-micmac-coach-carbone.md
devient une 404 sur https://datagir.netlify.app/blog/carbone/historique-calculateur-carbone-nos-gestes-climat-micmac-coach-carbone.md.

Pour le SEO mais surtout les pages référencent nos articles.

**Comment by florianpanchout** [comment]
C'est fait
