### ISSUE TITLE
Centrer et élargir le corps des articles

### ISSUE THREAD

**Issue by laem** [betagouv/datagir-site#8]
Je trouve cela bizarre d'avoir un en-tête centré puis un retour à gauche assez contraint de seulement 600px pour le corps de l'article.

Ce n'est pas bloquant, mais peut-être tester un centrage à 800px ou l'équivalent en rem ? 

![Capture d’écran du 2021-02-09 15-37-44](https://user-images.githubusercontent.com/1177762/107378944-c4b5b180-6aec-11eb-95c1-03e91090687f.png)

**Comment by florianpanchout** [comment]
C'était évidemment un bug d'affichage. 

(800px serait trop large pour la lisibilité)

**Comment by laem** [comment]
Ah oui en effet, les corps d'articles sont plutôt à 700 d'après mes petits tests :)

**Comment by florianpanchout** [comment]
Tout dépend de la taille du texte :) En général on considère idéal pour la lisibilité une ligne de 45 - 75 caractères (https://baymard.com/blog/line-length-readability)
